Plugin to accumulate segmentation confidence
kiwicampus/navigation2 pull request #12
Opened 2024-03-20 15:32 UTC by pepisg

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |

---

## Description of contribution in a few bullet points

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2024-03-20 19:52 UTC, jdgalviss commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +};
Why do CostHeuristicParams and ClassToCostManager structs have the same values? I couldn't find any instances of ClassToCostManager, it seems to be unused

2024-03-20 20:13 UTC, jdgalviss commented on nav2_costmap_2d/include/nav2_costmap_2d/semantic_segmentation_layer.hpp
> +// Define your custom struct.
This comment seems unrelated, please remove.

2024-03-20 20:16 UTC, jdgalviss commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> -    // });
Plese remove commented lines

2024-03-20 21:00 UTC, jdgalviss commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +sensor_msgs::msg::PointCloud2 visualizeTemporalTileMap(SegmentationTileMap& tileMap) {
Please add docstring

2024-04-08 13:58 UTC, pepisg commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +};
You're right, thanks!

2024-04-08 14:05 UTC, pepisg commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +sensor_msgs::msg::PointCloud2 visualizeTemporalTileMap(SegmentationTileMap& tileMap) {
added

2024-04-08 18:40 UTC, charlielito requested changes
Why are we merging this to an experimental branch?

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +            tile_map_.reserve(1e4);
why 1e4? please but a comment behind the logic

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +};
docstring?

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +        }
why does `worldToIndex` receive `x,y` but `indexToWorld` returns `TileWorldXY` ? Shouldn't `worldToIndex` also receive a `TileWorldXY` ?

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +            this->id_to_cost_[id] = cost;
`this->name_to_id_` is not the same as `nameToIdMap` ? why not just making a copy?

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/include/nav2_costmap_2d/semantic_segmentation_layer.hpp
> +#include "vision_msgs/msg/label_info.hzpp"
typo?

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/include/nav2_costmap_2d/semantic_segmentation_layer.hpp
> +    bool getSegmentationTileMaps(std::vector<std::pair<SegmentationTileMap::SharedPtr, SegmentationBuffer::SharedPtr>>& segmentation_tile_maps);
docstring please, is confusing that a function that starts with "get...TileMap" returns a bool

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> +    // confidence maps
this comment is no longer true right?

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> +      if(tile.second.size() >= cost_params.samples_to_max_cost && tile.second.getConfidenceSum() / tile.second.size() > cost_params.mark_confidence)
it could be more readable if you store in a variable `tile.second`

2024-04-08 18:40 UTC, charlielito commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> +      if(tile.second.size() >= cost_params.samples_to_max_cost && tile.second.getConfidenceSum() / tile.second.size() > cost_params.mark_confidence)
I think we could implement this slightly differently to be a little bit more general and easy to modify.
Inside the `tile` instead of tracking the sum of confidences, we could track all confidences in a queue. In this case we are just calculating the avg, we could in the future calculate the median or whatsoever instead of the mean for marking. What do you think?

2024-04-16 15:42 UTC, pepisg commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +        }
You're right, I think I will change indexToWorld to receive x,y instead because if I do it the other way around I will be forced to create a TileWorldXY each time, which could be expensive

2024-04-16 15:53 UTC, pepisg commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +            this->id_to_cost_[id] = cost;
fixed

2024-04-16 15:55 UTC, pepisg commented on nav2_costmap_2d/include/nav2_costmap_2d/semantic_segmentation_layer.hpp
> +    bool getSegmentationTileMaps(std::vector<std::pair<SegmentationTileMap::SharedPtr, SegmentationBuffer::SharedPtr>>& segmentation_tile_maps);
the segmentation tile map is passed by reference and is filled by the funciton. the bool return value means whether the map could be filled successfully. Adding that to the docstring

2024-04-16 16:04 UTC, pepisg commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> +      if(tile.second.size() >= cost_params.samples_to_max_cost && tile.second.getConfidenceSum() / tile.second.size() > cost_params.mark_confidence)
fixed

2024-04-16 16:12 UTC, pepisg commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> +      if(tile.second.size() >= cost_params.samples_to_max_cost && tile.second.getConfidenceSum() / tile.second.size() > cost_params.mark_confidence)
I think this needs to be done carefully due to performance reasons: the data structure that stores individual observations is a deque that can grow to up to ~75 elements in size (observations received at 15Hz over 5 seconds), doing anything that may involve going through the whole queue (ex: sorting to calculate the median) can increase the computational burden of the plugin significantly. I chose summing the confidence because I can keep track of the sum as I push and remove items, which at the time i want to run the heuristic to calculate the cost means just reading a variable.

I don't think we should change this to implement more complex operations until we find a good reason to do so. What do you think?

2024-04-16 16:13 UTC, pepisg commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> +    // confidence maps
fixed

2024-04-16 18:41 UTC, pepisg commented on nav2_costmap_2d/include/nav2_costmap_2d/segmentation_buffer.hpp
> +            tile_map_.reserve(1e4);
added

2024-04-16 18:41 UTC, pepisg commented on nav2_costmap_2d/include/nav2_costmap_2d/semantic_segmentation_layer.hpp
> +#include "vision_msgs/msg/label_info.hzpp"
thanks :facepalm:

2024-04-16 18:56 UTC, charlielito commented on nav2_costmap_2d/plugins/semantic_segmentation_layer.cpp
> +      if(tile.second.size() >= cost_params.samples_to_max_cost && tile.second.getConfidenceSum() / tile.second.size() > cost_params.mark_confidence)
I think makes sense then to leave this as it is

2024-04-16 18:59 UTC, charlielito approved these changes
LGTM. For the future, rename the "stable" branch to a different one :p

2024-04-24 13:51 UTC, merged